package:
  name: elemental-client
  version: "0.2.dev0"

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - elemental-core
    - elemental-kinds
  run:
    - python
    - requests
    - elemental-core
    - elemental-kinds

test:
  requires:
    - pytest
  imports:
    - elemental_client

about:
  home: https://github.com/artplusplus/elemental-client.
  summary: elemental-client provides an interface to an elemental-backend.
  license: Mozilla Public License 2.0 (MPL 2.0)
  license_file: LICENSE
